### PR TITLE
fix extends instructions

### PR DESCRIPTION
**Pull request by digikata**
Existing instructions cause a error on zola check
Error: Template 'index.html' is inheriting from 'themes/zola-clean-blog/templates/index.html', which doesn't exist or isn't loaded.

Knocking off themes lets the path resolve

### CODE REVIEW

**Comment by digikata** [comment]
I don't know if you're looking for pull requests, but this is a simple documentation fix.

**Review by thelema — APPROVED** [review]
I came to make the same change.  There are two instances of this fix needed, but this is in the right direction.
Edit: oops, only meant to approve the first commit, not the rest of these commits that I haven't reviewed yet (and one of which is breaking CI)

**Comment by thelema** [comment]
Note that the failure is:
```
11:17:55 PM: Error: Failed to render page '/opt/build/repo/content/pages/contact-us.md'
11:17:55 PM: Reason: Failed to render 'contact.html' (error happened in a parent template)
11:17:55 PM: Reason: Variable `config.extra.sidebar` not found in context while rendering 'contact.html'
```
I guess that the contact-us page needs to have sidebar elements specified.
I think that the right step is to remove that commit from this pull request.

**Comment by dave-tucker** [comment]
I fixed the README. If you'd like to contribute additional features then please open a new PR

**Pull request closed without merging**
